connect-base/0.1/docker-entrypoint.sh
connect-base/0.2/docker-entrypoint.sh
connect-base/0.3/docker-entrypoint.sh
kafka/0.1/docker-entrypoint.sh
kafka/0.2/docker-entrypoint.sh
kafka/0.3/docker-entrypoint.sh
zookeeper/0.1/docker-entrypoint.sh
zookeeper/0.2/docker-entrypoint.sh
zookeeper/0.3/docker-entrypoint.sh

Changed the Zookeeper, Kafka, and Kafka Connect images to optionally enable JMX.

DBZ-134 Added JMX support to Docker images

---

connect/0.5/Dockerfile

(Waiting for release to show up in Maven Central)

Updating Connect Docker image for release 0.5.1

---

build-debezium.sh
examples/mysql/0.6/inventory.sql
examples/postgres/0.6/Dockerfile
examples/postgres/0.6/inventory.sql

We'll also have to adapt the job on DockerHub for deploying that image.
https://issues.jboss.org/browse/DBZ-361

DBZ-361 Adding example image for Postgres

---

build-debezium.sh
examples/mongodb/0.6/Dockerfile
examples/mongodb/0.6/init-inventory.sh

https://issues.jboss.org/browse/DBZ-361

DBZ-361 Adding example image for MongoDB

---

build-all.sh
postgres/10.0/Dockerfile
postgres/10.0/README.md
postgres/10.0/docker-entrypoint-initdb.d/init-permissions.sh
postgres/10.0/postgresql.conf.sample

https://issues.jboss.org/browse/DBZ-426

DBZ-426 PostgreSQL 10.0 Image

---

examples/mongodb/0.7/Dockerfile
examples/mongodb/0.7/init-inventory.sh

https://issues.jboss.org/browse/DBZ-451

DBZ-451 Adding MongoDB example Docker image for 0.7

---

connect-base/0.7/docker-entrypoint.sh

https://issues.jboss.org/browse/DBZ-480

DBZ-480 Fixing wrong comment in docker-entrypoint.sh

---

kafka/0.6/Dockerfile
kafka/0.7/Dockerfile
zookeeper/0.6/Dockerfile
zookeeper/0.7/Dockerfile

https://issues.jboss.org/browse/DBZ-503

DBZ-503 Apache products can be downloaded from archive

---

postgres/10.0/Dockerfile
postgres/9.6/Dockerfile

https://issues.jboss.org/browse/DBZ-379

DBZ-379 Type metadata included

---

examples/mysql/0.7/inventory.sql

https://issues.jboss.org/browse/DBZ-463

DBZ-463 Aligned small typos

---

postgres/10.0/Dockerfile
postgres/9.6/Dockerfile

For PostGIS support in https://github.com/debezium/debezium/pull/374

[DBZ-507] Add PostGIS 2.4 to PostgreSQL images

---

kafka/0.7/Dockerfile

https://issues.jboss.org/browse/DBZ-489

DBZ-489 Remove unnecessary files from Kafka image

---

zookeeper/0.7/Dockerfile

https://issues.jboss.org/browse/DBZ-527

DBZ-527 Remove unnecessary files from ZooKeeper image

---

examples/mongodb/0.7/Dockerfile

https://issues.jboss.org/browse/DBZ-509

DBZ-509 Switch example image to 3.4

---

postgres/10.0/Dockerfile
postgres/9.6/Dockerfile

https://issues.jboss.org/browse/DBZ-526

DBZ-526 PostGIS can be removed from Postgres images

---

examples/mysql/0.8/inventory.sql

this will be used in the blog post to build DDD aggregates with kstreams
based on two topics (customers,addresses) with an 1:N relationship

DBZ-564 added an addresses relation with fictional records

---

connect-base/0.8/docker-entrypoint.sh

https://issues.jboss.org/browse/DBZ-702

DBZ-702 Hide JAAS config from log

---

connect/0.8/README.md

@jpechane A quick one as per the comment in the chat

Updating Connect Docker image readme

---

connect/0.8/Dockerfile
connect/0.8/Dockerfile.local
connect/0.8/README.md
connect/snapshot/Dockerfile

https://issues.jboss.org/browse/DBZ-20

DBZ-20 Add Oracle support

---

build-all.sh
postgres/10.0-alpine/Dockerfile
postgres/10.0-alpine/README.md
postgres/10.0-alpine/docker-entrypoint-initdb.d/init-permissions.sh
postgres/10.0-alpine/postgresql.conf.sample
postgres/9.6-alpine/Dockerfile
postgres/9.6-alpine/README.md
postgres/9.6-alpine/docker-entrypoint-initdb.d/init-permissions.sh
postgres/9.6-alpine/postgresql.conf.sample

Build Alpine Linux versions of the postgres images.
These images are much smaller than the default Debian-based images.

DBZ-705: Postgres alpine images

---

kafka/0.9/docker-entrypoint.sh

https://issues.jboss.org/browse/DBZ-890

DBZ-890 Option zookeeper no longer available

---

connect-base/0.8/docker-entrypoint.sh
connect-base/0.9/docker-entrypoint.sh

https://issues.jboss.org/browse/DBZ-861

DBZ-861 Mark further sensitive env vars

---

build-all.sh

https://issues.jboss.org/browse/DBZ-929
A one more change that was forgotten

DBZ-929 Use correct dir names

---

mongo-initiator/3.2/docker-entrypoint.sh
mongo-initiator/3.4/docker-entrypoint.sh
mongo-initiator/3.6/docker-entrypoint.sh
mongo-initiator/4.0/docker-entrypoint.sh

Mongo client 3.2.12 and 3.2.13 support invalid queries which was produced by the entrypoint script, now it takes in consideration the amount of replicas before putting the comma in the list.
The bug is better explained here: https://jira.mongodb.org/browse/SERVER-22053
With the old entrypoint: (Observe the leading comma within `members` obj)
```console
$ docker run --rm --name=mongo1 mongo:3.6 --replSet rs0 --oplogSize=2 --enableMajorityReadConcern
$ docker run -it --name mongo-init --rm -e REPLICASET=rs0 --link mongo1 debezium/mongo-initiator:3.2
+ /usr/bin/mongo --host 172.17.0.2 --port 27017 --eval 'config= {_id: "rs0", members:[ , {_id: 1, host: "172.17.0.2:27017", priority: 2 } ] };rs.initiate(config);'
MongoDB shell version: 3.2.21
connecting to: 172.17.0.2:27017/test
{
"ok" : 0, …
```

DBZ-974 Fix Replica set Initialization

---

postgres/10-alpine/Dockerfile
postgres/10/Dockerfile
postgres/11-alpine/Dockerfile
postgres/11/Dockerfile
postgres/9.6-alpine/Dockerfile
postgres/9.6/Dockerfile

https://issues.jboss.org/browse/DBZ-1083

DBZ-1083 RDS does not use include-unchanged-toast

---

connect/0.9/Dockerfile

https://issues.jboss.org/browse/DBZ-1084

DBZ-1084 Move SQL Server to core modules

---

tooling/Dockerfile

https://issues.jboss.org/browse/DBZ-1125?focusedCommentId=13693786&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13693786

DBZ-1125 Added pgcli and mycli

---

zookeeper/0.9/README.md

https://issues.jboss.org/browse/DBZ-1231

DBZ-1231 Document txn directory

---

tooling/Dockerfile

- Upgrade to Fedora 30
- Upgrade Kafkacat to 1.4.0

DBZ-1301 Upgrade Docker tooling image

---

zookeeper/0.10/Dockerfile

https://issues.jboss.org/browse/DBZ-1298

DBZ-1298 Upgrading to ZooKeeper 3.4.14

---

examples/postgres/0.10/Dockerfile

https://issues.jboss.org/browse/DBZ-1302

DBZ-1302 Upgrading PG example image to 11

---

connect-base/0.10/docker-maven-download.sh
connect/0.10/Dockerfile
postgres/10-alpine/Dockerfile
postgres/11-alpine/Dockerfile
postgres/9.6-alpine/Dockerfile

https://github.com/debezium/debezium/pull/899

DBZ-1304 Fix release pipline

---

postgres/10-alpine/Dockerfile
postgres/11-alpine/Dockerfile
postgres/9.6-alpine/Dockerfile

https://issues.jboss.org/browse/DBZ-1307

DBZ-1307 Build proj4 from source to have ver 5

---

postgres/9.6-alpine/Dockerfile

https://issues.jboss.org/browse/DBZ-1351

DBZ-1307 Enable PostGIS for Alpine 9.6

---

image-sync/Dockerfile
image-sync/README.md
image-sync/sync.sh

https://issues.jboss.org/browse/DBZ-1178

DBZ-1178 Sync between Docker Hub and Quay

---

build-all.sh
postgres/12-alpine/Dockerfile
postgres/12-alpine/README.md
postgres/12-alpine/docker-entrypoint-initdb.d/init-permissions.sh
postgres/12-alpine/postgresql.conf.sample
postgres/12/Dockerfile
postgres/12/README.md
postgres/12/docker-entrypoint-initdb.d/init-permissions.sh
postgres/12/postgresql.conf.sample

https://issues.jboss.org/browse/DBZ-1542

DBZ-1542 Support for Postgres 12 images

---

postgres/10-alpine/Dockerfile
postgres/10/Dockerfile
postgres/11-alpine/Dockerfile
postgres/11/Dockerfile
postgres/12-alpine/Dockerfile
postgres/12/Dockerfile
postgres/9.6-alpine/Dockerfile
postgres/9.6/Dockerfile

https://issues.jboss.org/browse/DBZ-1549

DBZ-1549 Switch to two-phase build for postgres

---

postgres/10-alpine/README.md
postgres/10/README.md
postgres/11-alpine/README.md
postgres/11/README.md
postgres/12-alpine/README.md
postgres/12/README.md
postgres/9.6-alpine/README.md
postgres/9.6/README.md

@Naros, @jcechace, could either of you review and merge this one? Thanks!

DBZ-1549 README update

---

build-all.sh
mongo-initiator/4.2/Dockerfile
mongo-initiator/4.2/README.md
mongo-initiator/4.2/docker-entrypoint.sh

https://issues.jboss.org/browse/DBZ-1626

DBZ-1626 MongoDB 4.2 image

---

kafka/1.0/Dockerfile
zookeeper/1.0/Dockerfile

https://issues.jboss.org/browse/DBZ-969

DBZ-969 Upgrading docker containers to JDK 11

---

awestruct/Dockerfile

https://issues.redhat.com/browse/DBZ-1719

DBZ-1719 Upgrade to Ruby 2.4

---

connect/1.1/Dockerfile
connect/1.1/Dockerfile.local
connect/snapshot/Dockerfile

https://issues.redhat.com/browse/DBZ-695
Don't merge yet, needs the connector SHA to be known.

DBZ-695 Adding DB2 connector to connector image

---

connect-base/1.1/docker-entrypoint.sh

https://issues.redhat.com/browse/DBZ-1843

DBZ-1843 Change logging level only when env var is set

---

connect-base/1.1/Dockerfile
connect-base/1.2/Dockerfile

https://issues.redhat.com/browse/DBZ-1915

DBZ-1915 Upgrade Avro Converter

---

connect-base/1.2/Dockerfile

https://issues.redhat.com/browse/DBZ-1981

DBZ-1981 Upgrade to Confluent Platform 5.5.0

---

connect-base/1.2/Dockerfile

https://issues.redhat.com/browse/DBZ-2082

DBZ-2082 New Avro converter dependencies

---

build-debezium.sh
server/1.2/Dockerfile
server/1.2/README.md
server/1.3/Dockerfile
server/1.3/README.md

https://issues.redhat.com/browse/DBZ-2147

DBZ-2147 Image for Debezium Server

---

connect-base/1.3/Dockerfile

https://issues.redhat.com/browse/DBZ-2509

DBZ-2509 Upgrade Jackson to 2.10.2

---

connect-base/1.3/README.md
connect-base/1.3/docker-entrypoint.sh
connect-base/1.3/docker-maven-download.sh
connect/1.2/Dockerfile.local
connect/1.3/Dockerfile
connect/1.3/Dockerfile.local
connect/1.3/README.md
connect/snapshot/Dockerfile
server/1.2/Dockerfile
server/1.3/Dockerfile

Applied on top of https://github.com/debezium/docker-images/pull/189

Debezium Server repo configurable

---

connect-base/1.3/Dockerfile
connect-base/1.3/README.md
connect-base/1.3/docker-entrypoint.sh
kafka/1.3/Dockerfile

https://issues.redhat.com/browse/DBZ-2541

DBZ-2541 Make log4j root loggers configurable in connect-base image

---

connect-base/1.4/docker-maven-download.sh
connect/1.4/Dockerfile
connect/1.4/Dockerfile.local
connect/snapshot/Dockerfile
server/1.4/Dockerfile
server/1.4/README.md

https://issues.redhat.com/browse/DBZ-2618

DBZ-2618 Support Vitess in local and snapshot docker builds

---

connect-base/1.3/docker-maven-download.sh
connect-base/1.4/docker-maven-download.sh
connect/1.3/Dockerfile
connect/1.4/Dockerfile
connect/1.4/Dockerfile.local
connect/snapshot/Dockerfile
server/1.4/Dockerfile
server/1.4/README.md

https://issues.redhat.com/browse/DBZ-2611
Built on top of https://github.com/debezium/docker-images/pull/192

DBZ-2611 Align 1.3 to new release pipeline

---

awestruct/Dockerfile

https://issues.redhat.com/browse/DBZ-2674

DBZ-2674 Update debezium/awestruct to use Antora 2.3.4

---

connect-base/1.3/Dockerfile
connect-base/1.4/Dockerfile

https://issues.redhat.com/browse/DBZ-2561

DBZ-2561 Upgrade apicurio to 1.3.2.Final

---

connect/1.4/README.md

Slight fix to 1.4 documentation grammar.

Fix 1.4 README typo

---

connect-base/1.5/docker-entrypoint.sh

https://issues.redhat.com/browse/DBZ-3070

DBZ-3070 Match underscore in prefix too

---

kafka/1.5/docker-entrypoint.sh

The variable `HEAP_OPTS` value needs to be used.

DBZ-3006: Update Kafka Docker image Heap

---

postgres/13-alpine/Dockerfile
postgres/13-alpine/README.md
postgres/13-alpine/docker-entrypoint-initdb.d/init-permissions.sh
postgres/13-alpine/postgresql.conf.sample
postgres/13/Dockerfile
postgres/13/README.md
postgres/13/docker-entrypoint-initdb.d/init-permissions.sh
postgres/13/postgresql.conf.sample

https://issues.redhat.com/browse/DBZ-3022

DBZ-3022 Images for Postgres 13

---

connect-base/1.4/docker-entrypoint.sh
connect-base/1.5/docker-entrypoint.sh

https://issues.redhat.com/browse/DBZ-3103

DBZ-3103 Process var values with spaces

---

build-debezium.sh
ui/1.5/Dockerfile

https://issues.redhat.com/browse/DBZ-3027

DBZ-3027 Add Debezium UI image

---

connect-base/1.5/docker-entrypoint.sh

https://issues.redhat.com/browse/DBZ-3245

DBZ-3245 Catch first equal sign while separating key/value

---

connect-base/1.5/Dockerfile
kafka/1.5/Dockerfile

https://issues.redhat.com/browse/DBZ-2872

DBZ-2872 Upgrade Kafka to 2.7.0

---

README.md

https://issues.redhat.com/browse/DBZ-3383

DBZ-3383 Fix wrong badge on Docker Hub

---

connect-base/1.6/README.md
connect-base/1.6/docker-entrypoint.sh

https://issues.redhat.com/browse/DBZ-3082

DBZ-3082 Provide Flight Recorder support

---

connect-base/1.6/Dockerfile
connect-base/1.6/docker-maven-download.sh

https://issues.redhat.com/browse/DBZ-3171

DBZ-3171 Use Apicurio 2

---

server/1.5/Dockerfile
server/1.6/Dockerfile

https://issues.redhat.com/browse/DBZ-3659

DBZ-3659 Install missing gzip package

---

kafka/1.7/docker-entrypoint.sh

https://issues.redhat.com/browse/DBZ-3791

DBZ-3791 Fixed incorrect regex

---

build-all.sh
build-debezium.sh
build-mongo.sh
build-postgres.sh
connect/snapshot/Dockerfile

https://issues.redhat.com/browse/DBZ-3809

DBZ-3809 Support images push from Jenkins

---

zookeeper/1.7/Dockerfile

https://issues.redhat.com/browse/DBZ-3914

DBZ-3914 Do not download from archive.apache.org

---

examples/mysql/1.7/Dockerfile

https://issues.redhat.com/browse/DBZ-3936

DBZ-3936 Upgrade MySQL example image to 8.0

---

zookeeper/1.6/Dockerfile

https://issues.redhat.com/browse/DBZ-3950

DBZ-3950 Upgrade ZooKeeper for 1.6

---

base/latest/Dockerfile
build-debezium.sh
connect-base/1.7/Dockerfile
kafka/1.7/Dockerfile
zookeeper/1.7/Dockerfile

https://issues.redhat.com/browse/DBZ-3939
https://issues.redhat.com/browse/DBZ-3944

DBZ-3939 Migrate to UBI image from Fabric8

---

postgres/12/Dockerfile
postgres/13/Dockerfile

https://issues.redhat.com/browse/DBZ-4080

DBZ-4080 Upgrade to PostGIS 3

---

.github/workflows/image-builds-auth.yml
.github/workflows/image-builds-unauth.yml
build-tool-images.sh
tooling/Dockerfile
website-builder/Dockerfile

https://issues.redhat.com/browse/DBZ-3907

DBZ-3907 Build debezium tool images

---

tooling/Dockerfile

https://issues.redhat.com/browse/DBZ-4258

DBZ-4258 Upgrade content for 1.2 image

---

kafka/1.7/Dockerfile
kafka/1.8/Dockerfile
zookeeper/1.7/Dockerfile
zookeeper/1.8/Dockerfile

https://issues.redhat.com/browse/DBZ-4160
@jpechane, this should go into tomorrow's release. Just realizing though after re-reading the original issue, that this was reported for the Kafka image as well. I'll amend this PR accordingly.

DBZ-4160 Removing relative paths from ZooKeeper classpath

---

examples/mongodb/1.8/Dockerfile
examples/mongodb/1.8/init-inventory.sh

https://issues.redhat.com/browse/DBZ-4205

DBZ-4205 Add db-wide changeStream privilege

---

examples/mongodb/1.8/Dockerfile

https://issues.redhat.com/browse/DBZ-3938

DBZ-3938 Use MongoDB 5.0 as the example

---

build-debezium.sh
build-mongo.sh
build-postgres.sh
build-tool-images.sh

https://issues.redhat.com/browse/DBZ-4006

DBZ-4006 Add script to push connector images to Quay.io

---

base/latest/Dockerfile
kafka/1.7/Dockerfile
kafka/1.8/Dockerfile
zookeeper/1.7/Dockerfile
zookeeper/1.8/Dockerfile

https://issues.redhat.com/browse/DBZ-4447

DBZ-4447 Patch for CVE-2021-4104

---

website-builder/Dockerfile

https://issues.redhat.com/browse/DBZ-4508

DBZ-4508 Remove unnecessary commands

---

connect-base/1.9/Dockerfile

https://issues.redhat.com/browse/DBZ-4569

DBZ-4569 Upgrade Apicurio and Confluent to the latest version

---

connect-base/1.9/Dockerfile

https://issues.redhat.com/browse/DBZ-4935

DBZ-4935 Add missing guava avro dependency

---

kafka/2.0/Dockerfile

https://issues.redhat.com/browse/DBZ-5144

DBZ-5144 Upgrade Kafka to 3.2.0

---

base/latest/Dockerfile

https://issues.redhat.com/browse/DBZ-5461

DBZ-5461 Upgrade base image to Fedora 36

---

connect-base/2.0/Dockerfile

https://issues.redhat.com/browse/DBZ-5549

DBZ-5549 Upgrade apicurio to 2.2.5.Final

---

postgres/10/Dockerfile
postgres/11/Dockerfile
postgres/12/Dockerfile
postgres/13/Dockerfile
postgres/14/Dockerfile
postgres/15/Dockerfile
postgres/9.6/Dockerfile

https://issues.redhat.com/browse/DBZ-5823

DBZ-5823 Upgrade Postgres to Debian 11

---

base/latest/Dockerfile

https://issues.redhat.com/browse/DBZ-5467

DBZ-5467 Upgrade images to Fedora 37

---

zookeeper/2.0/Dockerfile
zookeeper/2.1/Dockerfile
zookeeper/2.2/Dockerfile

https://issues.redhat.com/browse/DBZ-5972

DBZ-5972 Download Zookeeper from archive URL

---

website-builder/Dockerfile

https://issues.redhat.com/browse/DBZ-5971

DBZ-5971 Jekyll with native sassc not supported by image

---

connect-base/2.2/Dockerfile

https://issues.redhat.com/browse/DBZ-5977

DBZ-5977 Upgrade Apicurio to 2.4.1.Final

---

connect-base/2.2/Dockerfile
connect-base/2.2/docker-entrypoint.sh
connect-base/2.2/docker-maven-download.sh

https://issues.redhat.com/browse/DBZ-6323

DBZ-6323 Add Jolokia to Debezium connect image

---

postgres/11-alpine/Dockerfile
postgres/12-alpine/Dockerfile
postgres/13-alpine/Dockerfile
postgres/14-alpine/Dockerfile
postgres/15-alpine/Dockerfile

https://issues.redhat.com/browse/DBZ-6506

DBZ-6506 use LLVM/Clang 15 explicitly

---

server/snapshot/Dockerfile
server/snapshot/README.md

https://issues.redhat.com/browse/DBZ-6536

DBZ-6536 Dockerfile for server nightly images.

---

operator/2.3/Dockerfile

https://issues.redhat.com/browse/DBZ-6542

DBZ-6542 release image for debezium operator

---

operator/snapshot/Dockerfile

https://issues.redhat.com/browse/DBZ-6541

DBZ-6541 nighly image for debezium operator

---

build-debezium-multiplatform.sh

https://issues.redhat.com/browse/DBZ-6546

DBZ-6546 adding operator image to build script

---

website-builder/Dockerfile

https://issues.redhat.com/browse/DBZ-7269

DBZ-7269 Prescibe Ruby 2 bundler version

---

postgres/10/Dockerfile
postgres/11/Dockerfile
postgres/12/Dockerfile
postgres/13/Dockerfile
postgres/14/Dockerfile
postgres/15/Dockerfile
postgres/16/Dockerfile
postgres/9.6/Dockerfile

https://issues.redhat.com/browse/DBZ-7475

DBZ-7475 Install c-lang/llvm 11 for Postgres build process

---

base/latest/Dockerfile

Fixes https://issues.redhat.com/browse/DBZ-7832

DBZ-7832 Bump base image to Fedora 38

---

build-debezium.sh
examples/mariadb/2.7/Dockerfile
examples/mariadb/2.7/inventory.sql
examples/mariadb/2.7/mysql.cnf

https://issues.redhat.com/browse/DBZ-7785

DBZ-7785 Add `example-mariadb` container

---

build-all.sh

https://issues.redhat.com/browse/DBZ-7128

DBZ-7128 Remove PostgreSQL 10 and 11, Add PostgreSQL 16

---

website-builder/Dockerfile

Jira: [DBZ-7916](https://issues.redhat.com/browse/DBZ-7916)
Supporting PR https://github.com/debezium/debezium.github.io/pull/1038

DBZ-7916: Update Ruby to 3.x

---

connect-base/2.7/docker-entrypoint.sh
kafka/2.7/docker-entrypoint.sh

https://issues.redhat.com/browse/DBZ-7982

DBZ-7982 Replace egrep with grep

---

operator/3.0/Dockerfile
operator/snapshot/Dockerfile
server/3.0/Dockerfile
server/snapshot/Dockerfile

https://issues.redhat.com/browse/DBZ-7224
Follows on https://github.com/debezium/debezium/pull/5658

DBZ-7224 Switched operator and server image to JDK 21

---

postgres/15/Dockerfile
postgres/16/Dockerfile

https://issues.redhat.com/browse/DBZ-8121

DBZ-8121 Install pgvector extension

---

server/3.0/Dockerfile
server/3.0/Dockerfile.local

relates to https://github.com/debezium/debezium-server/pull/120 and should probably be merged right before release

DBZ-8206 Changed server config volume path

---

connect-base/3.0/Dockerfile
connect-base/3.0/docker-maven-download.sh

https://issues.redhat.com/browse/DBZ-8175

DBZ-8175 Remove extra Jackson libs from Apicurio dir

---

base/latest/Dockerfile

https://issues.redhat.com/browse/DBZ-8266

DBZ-8266 Bump container images to Fedora 40

---

examples/mysql-replication/master/2.7/Dockerfile
examples/mysql-replication/master/3.0/Dockerfile
examples/mysql-replication/master/3.1/Dockerfile
examples/mysql-replication/replica/2.7/Dockerfile
examples/mysql-replication/replica/3.0/Dockerfile
examples/mysql-replication/replica/3.1/Dockerfile

https://issues.redhat.com/browse/DBZ-8633

DBZ-8633 Use correct folder with mysql configuration

---

build-debezium-multiplatform.sh
build-debezium.sh
conductor/snapshot/Dockerfile

closes: https://issues.redhat.com/browse/DBZ-8605

DBZ-8605 Add snapshot dockerfile for debezium platform conductor

---

.github/workflows/image-builds-unauth.yml

DBZ-8605 Add 3.1 for conductor

---

examples/mysql-replication/master/2.7/Dockerfile
examples/mysql-replication/master/2.7/master.cnf
examples/mysql-replication/master/3.0/Dockerfile
examples/mysql-replication/master/3.0/master.cnf
examples/mysql-replication/master/3.1/Dockerfile
examples/mysql-replication/master/3.1/master.cnf
examples/mysql-replication/replica/2.7/Dockerfile
examples/mysql-replication/replica/2.7/slave.cnf
examples/mysql-replication/replica/3.0/Dockerfile
examples/mysql-replication/replica/3.0/slave.cnf
examples/mysql-replication/replica/3.1/Dockerfile
examples/mysql-replication/replica/3.1/slave.cnf

Previous fix worked, I was confused by the `latest` tag, which made me think that it didn't work, but this is more proper fix (if this sounds confusing, please check DBZ-8633 where I tried to explain little bit more:-).
https://issues.redhat.com/browse/DBZ-8633

DBZ-8633 Remove directive to include non-existing directory

---

postgres/12/Dockerfile
postgres/13/Dockerfile
postgres/14/Dockerfile
postgres/15/Dockerfile
postgres/16/Dockerfile
postgres/17/Dockerfile

https://issues.redhat.com/browse/DBZ-8670

DBZ-8670 Upgrade libprotobuf

---

connect-base/2.6/docker-entrypoint.sh
connect-base/2.7/docker-entrypoint.sh
connect-base/3.0/docker-entrypoint.sh
connect-base/3.1/docker-entrypoint.sh

This is a micro PR to fix a little typo, I did not open an issue on your bugtracker but I can do if you need it.

fix: Fix a little typo in a comment

---

build-all-multiplatform.sh

https://issues.redhat.com/browse/DBZ-8713

DBZ-8713 Disable ARM images for PostgreSQL

---

connect-base/3.1/Dockerfile

https://issues.redhat.com/browse/DBZ-8709

chore: add args to choose which external libs to load

---

build-debezium-multiplatform.sh
build-debezium.sh
build-postgres-multiplatform.sh
build-postgres.sh

relates to: https://github.com/debezium/debezium/pull/6215

DBZ-8731 Add dry run option

---

examples/mariadb/3.0/mysql.cnf
examples/mariadb/3.1/mysql.cnf

https://issues.redhat.com/browse/DBZ-8755

DBZ-8755 Add position of the next event in the binary log

---

website-builder/Dockerfile

https://issues.redhat.com/browse/DBZ-9036

DBZ-9036 Update website builder to Antora 3.1.10

---

examples/mongodb/3.0/Dockerfile
examples/mongodb/3.0/init-inventory.sh
examples/mongodb/3.1/Dockerfile
examples/mongodb/3.1/init-inventory.sh
examples/mongodb/3.2/Dockerfile
examples/mongodb/3.2/init-inventory.sh

Reverts debezium/container-images#453

Revert "DBZ-9061 Fix example mongodb image"

---

.github/workflows/image-builds-auth.yml
.github/workflows/image-builds-unauth.yml
build-debezium-multiplatform.sh
build-debezium.sh
script-functions/common.sh

closes: https://issues.redhat.com/browse/DBZ-8914

DBZ-8914 Add additional semver tag to images

---

server/3.3/README.md

https://issues.redhat.com/browse/DBZ-9282

DBZ-9282 Document JMX details in Debezium Server README
