debezium/container-images

kafka/0.1/Dockerfile, zookeeper/0.1/Dockerfile
The Zookeeper and Kafka images were adding specific configuration files as the root user rather than the particular user for the image. This caused issues when starting containers.
=> DBZ-46 Corrected the permissions of the configuration files

build-all.sh, build-mongo.sh, mongo/3.2/mongo-replicaset-initiator/Dockerfile, mongo/3.2/mongo-replicaset-initiator/docker-entrypoint.sh
Created an image that can be used to initiate a MongoDB replica set. 
All MongoDB nodes must already be running before the replica set can be initiated. This container can be run after containers for the MongoDB nodes are running, and when linked to the running MongoDB containers will initiate the replica set with the addresses of the linked primary MongoDB node and any number of linked secondary MongoDB nodes..
=> DBZ-2 Added Docker image that can initiate a MongoDB replica set

build-all.sh, build-postgres.sh, postgres/9.6/Dockerfile, postgres/9.6/postgresql.conf.sample
The docker image uses the base Postgres 9.6 image and [my local decoderbufs fork](https://github.com/hchiorean/decoderbufs). 
The difference between the main repository and my fork is atm.:
* removal of the PostGIS dependency
* change of the Proto Java package names and classes
Ideally this Docker image should use a decoderbufs fork from the main [DBZ repository](https://github.com/debezium) which we can then modify as we see fit.
To validate that the docker image actually works, I've updated my [DBZ-3 branch](https://github.com/hchiorean/debezium/tree/DBZ-3) and the code for the [Postgres connector](https://github.com/hchiorean/debezium/tree/DBZ-3/debezium-connector-postgres) to use the `proto` file from the plugin, generate the appropriate Java classes (via a Maven plugin) and test that …
=> DBZ-3 Creates a docker image to be used with the decoderbufs PG plugin

postgres/9.6/Dockerfile, postgres/9.6/postgresql.conf.sample
It also updates the Docker image to use tag `0.3.0` of the plugin
=> DBZ-3 Updates the PG server configuration to allow more WAL sender processes and replication slots

build-debezium.sh
A typo in https://github.com/debezium/docker-images/pull/56 spotted too late
=> DBZ-361 Fixed MongoDB exmaple image name

kafka/0.6/Dockerfile
@jpechane Seems we forgot to apply that to 0.6, too. I'll push it myself.
=> DBZ-367 Kafka version promoted to 0.11.0.1

kafka/0.9/Dockerfile, zookeeper/0.9/Dockerfile
https://issues.jboss.org/browse/DBZ-939
Base image for Docker images is currently "fabric8/java-jboss-openjdk8-jdk", which is marked as deprecated (cf https://hub.docker.com/r/fabric8/java-jboss-openjdk8-jdk/ or https://github.com/fabric8io-images/java/pull/24).
=> DBZ-939 Replace deprecated base image by java-centos-openjdk8-jdk

build-all.sh, build-mongo.sh, mongo-initiator/3.4/Dockerfile, mongo-initiator/3.4/README.md, mongo-initiator/3.4/docker-entrypoint.sh, mongo-initiator/3.6/Dockerfile, mongo-initiator/3.6/README.md, mongo-initiator/3.6/docker-entrypoint.sh, mongo-initiator/4.0/Dockerfile, mongo-initiator/4.0/README.md, mongo-initiator/4.0/docker-entrypoint.sh, mongo-initiator/latest/Dockerfile, mongo-initiator/latest/README.md, mongo-initiator/latest/docker-entrypoint.sh
This allows to build mongo-initiator for all the currently and future supported versions.
This becomes essential to deliver DBZ-974 we can't use mongo-initiator:3/2 with a MongoDB Server 4.0
=> DBZ-974 Build mongo-init in supported versions

tooling/Dockerfile
https://issues.jboss.org/browse/DBZ-1148
@jpechane, I noticed that building kafkacat from source isn't 100% reproduceable despite building a specific tag/version: the bootstrap.sh script obtains some dependencies (librdkafka) by getting their source from their master branch.
Can you tag a version of the _debezium/tooling_ image, e.g. 0.1, so we have a stable, referenceable version of it? Thanks!
=> DBZ-1148 Using Kafkacat 1.4.0-RC1

awestruct/Dockerfile
https://issues.jboss.org/browse/DBZ-317
This PR simply makes sure that the _Antora_ framework is included as part of the website Awestruct docker image that builds our website.  We'll need to make sure this image is pulled down by everyone and any automated build process to guarantee that _Antora_ is available.
=> DBZ-317 Include Antora in the awestruct docker image

awestruct/Dockerfile
https://issues.redhat.com/browse/DBZ-1713
While upgrading the image, I noticed an issue with rdoc saying that we had some version incompats.  The warning suggested using v6.2.0 which I also changed.  I didn't see any issues with either change, let me know if we need to make any other changes @jpechane or @gunnarmorling.
Thanks!
=> DBZ-1713 Upgrade Antora to 2.3.0-alpha2

awestruct/Dockerfile
https://issues.redhat.com/browse/DBZ-1719
=> DBZ-1719 Upgrading to Ruby 2.4 as that's needed by Awestruct 0.6.0

awestruct/Dockerfile
Reverts debezium/docker-images#159
=> Revert "DBZ-1719 Upgrading to Ruby 2.4 as that's needed by Awestruct 0.6.0"

examples/mongodb/1.2/init-inventory.sh
Backwards compatible. Adds ability to specify replica hostname as
```/usr/local/bin/init-inventory.sh -h mongo.debezium-mongo.svc.cluster.local```
or 
```/usr/local/bin/init-inventory.sh --hostname mongo.debezium-mongo.svc.cluster.local```
This is especially useful in OCP where ```hostname``` resolves to pod hostname, however the service name is required in order for the replica to work correctly.
=> Ability to explicitly specify replica hostname for Mongo example image

connect-base/1.2/Dockerfile, connect-base/1.2/README.md, connect-base/1.2/docker-entrypoint.sh, connect-base/1.2/docker-maven-download.sh, connect-base/1.3/Dockerfile, connect-base/1.3/README.md, connect-base/1.3/docker-entrypoint.sh, connect-base/1.3/docker-maven-download.sh, connect/1.2/README.md, connect/1.3/README.md
https://issues.jboss.org/browse/DBZ-2083
I added an optional env var `DEBEZIUM_ENABLE_APICURIO`.
When it's set to `DEBEZIUM_ENABLE_APICURIO=1` it'll symlink Apicurio distro JARs to debezium converters in `$KAFKA_CONNECT_PLUGINS_DIR` (/kafka/connect/).
I added this to images version 1.2 and 1.3
=> DBZ-2083 add Apicurio converters

connect-base/1.2/README.md, connect-base/1.2/docker-entrypoint.sh, connect-base/1.3/README.md, connect-base/1.3/docker-entrypoint.sh, connect/1.2/README.md, connect/1.3/README.md
Related to https://github.com/debezium/docker-images/pull/173#issuecomment-655889269 in #173 here's the renaming PR to rename the env var from `DEBEZIUM_ENABLE_APICURIO` to `ENABLE_APICURIO_CONVERTERS`
FYI @jpechane
=> DBZ-2083 rename env var to enable Apicurio converters

connect/1.5/README.md
According to [this](https://github.com/apache/kafka/commit/cfa6a78c7c2529839d2f3cb1129098f2e552fd72) change. `KAFKA_HEAP_OPTS` is `2GB` by default
=> Update kafka connect image README

connect-base/1.4/docker-entrypoint.sh, connect-base/1.5/docker-entrypoint.sh
Please refer to: https://issues.redhat.com/browse/DBZ-3019
As requested in the issue commentary, a change for this script.
I imagine a bash guru could optimize the value extraction of this code into a single line. 
I have changed the log4j creation code for completion, but this is likely unnecessary due to the constraints on package names.
=> Potential fix for hypen-containing environment variables: DBZ-3019

website-builder/Dockerfile
The brackets are converted to volumes too so they need to be removed
=> Use correct volumes for website

connect-base/1.6/Dockerfile
https://issues.redhat.com/browse/DBZ-2547
=> DBZ-2547 Include libaio for Oracle Instant Client compatibility

website-builder/Dockerfile
https://issues.redhat.com/browse/DBZ-3903
@jpechane, this gave me trouble after some Docker upgrade, and I don't think it ever was needed anyways. How do we re-publish this image, is there a Jenkins job for it, too?
=> DBZ-3903 Removing unnecessary VOLUME instruction

examples/mysql-gtids/1.7/Dockerfile, examples/mysql-gtids/1.7/inventory.sql, examples/mysql-gtids/1.7/mysql.cnf, examples/mysql/1.7/inventory.sql, examples/mysql/1.7/mysql.cnf
https://issues.redhat.com/browse/DBZ-3944
Below 2 lines from `examples/mysql/1.7/inventory.sql` are non compliant with MySQL 8.0 syntax
```sql
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'replicator' IDENTIFIED BY 'replpass';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT  ON *.* TO 'debezium' IDENTIFIED BY 'dbz';
```
this is because `GRANT` syntax in 8.0 no more accepts auth_options as it was in 5.7
```
auth_option: {
IDENTIFIED BY 'auth_string'
| IDENTIFIED WITH auth_plugin
| IDENTIFIED WITH auth_plugin BY 'auth_string'
| IDENTIFIED WITH auth_plugin AS 'auth_string'
| IDENTIFIED BY PASSWORD 'auth_string'
}
```
This is now exclusive to `CREATE` statements only.
I see the image was recently updated. This prevents the image with defaults to start …
=> DBZ-3944 Fix for incorrect syntax in MySQL 8.0 example image💉

postgres/13/README.md
I updated the text of readme that mentioned that this image is based `postgres:12`  to correctly mention `postgres:13` ( as seen in line 37 https://github.com/debezium/docker-images/blob/master/postgres/13/Dockerfile )
=> Corrected the Postgres version in README.md

connect-base/1.8/Dockerfile, connect/1.8/Dockerfile, connect/1.8/Dockerfile.local, connect/snapshot/Dockerfile
Hey @jpechane, trivial fix, but I'm wondering how this could happen. Aren't those versions pulled up automatically during the release or something?
=> [release] Updating base image reference

ui/1.7/README.md, ui/1.8/README.md, ui/1.9/README.md
PR: https://github.com/debezium/debezium-ui/pull/398 changed the kafka connect environment variable name from `kafka.connect.uri` to `kafka.connect.uris`.
This PR updates the docker image documentation to reflect these new expectation.
=> Fix Kafka Connect Env var documentation.

connect/0.1/README.md, connect/0.10/README.md, connect/0.2/README.md, connect/0.3/README.md, connect/0.4/README.md, connect/0.5/README.md, connect/0.6/README.md, connect/0.7/README.md, connect/0.8/README.md, connect/0.9/README.md, connect/1.0/README.md, connect/1.1/README.md, connect/1.2/README.md, connect/1.3/README.md, connect/1.4/README.md, connect/1.5/README.md, connect/1.6/README.md, connect/1.7/README.md, connect/1.9/README.md
changed the kafka connect environment variable pattern example.
This PR updates the docker image documentation to reflect these new expectation.
=> Fix kafka connect property example documentation

kafka/1.8/docker-entrypoint.sh, kafka/1.9/docker-entrypoint.sh
Since Kafka version 3.0.0 `--zookeeper` flag was removed from Kafka
executables. The option is replaced by `--bootstrap-server`
option [1, 2]. Update docker images entrypoints to use this option.
[1] https://cwiki.apache.org/confluence/display/KAFKA/KIP-604%3A+Remove+ZooKeeper+Flags+from+the+Administrative+Tools
[2] https://issues.apache.org/jira/browse/KAFKA-10104
https://issues.redhat.com/browse/DBZ-4844
=> DBZ-4844 Remove --zookeeper flag from startup script

build-debezium-multiplatform.sh
Similar to https://github.com/docker/build-push-action/issues/452
Which seems to be related to a bug in containerd https://github.com/containerd/containerd/pull/6995
[quay.io](http://quay.io/) probably responds with redirect when pushing a new tag which has a matching hash of already existing tag. This unfortunately causes buildx builder to fail. Based on testing this seems to help.
=> DBZ-5213 Adding unique label when building multiarch images 

examples/postgres/2.0/Dockerfile, examples/postgres/2.1/Dockerfile
@jpechane, @Naros, a quick version update to the Postgres example images for 2.0 and 2.1. I'm still fighting to get my Jira account unlocked (I may have to create a new account potentially...). So if you want to have a ticket for this, could you create one and reference it in the commit message? Thanks a lot!
There's some cool logical replication improvements in PG 15 (which is what made me look into this), see [this post](http://amitkapila16.blogspot.com/2022/11/logical-replication-improvements-in.html) for details. For instance, publications can be limited to specific rows via custom WHERE clauses (akin to what we already support for snapshot queries).
https://issues.redhat.com/browse/DBZ-5860
=> [examples] Upgrading to Postgres 15

tooling/Dockerfile
https://issues.redhat.com/browse/DBZ-6642
=> DBZ-6642 Upgrade kcctl to 1.0.0.Beta3

kafka/2.3/Dockerfile, zookeeper/2.3/Dockerfile
[DBZ-6047](https://issues.redhat.com/browse/DBZ-6047)
Depends on https://github.com/debezium/debezium/pull/4617
=> DBZ-6047 Upgrade to Kafka 3.5.0

build-all-multiplatform.sh, examples/postgres/2.4/Dockerfile, postgres/16-alpine/Dockerfile, postgres/16-alpine/README.md, postgres/16-alpine/docker-entrypoint-initdb.d/init-permissions.sh, postgres/16-alpine/postgresql.conf.sample, postgres/16/Dockerfile, postgres/16/README.md, postgres/16/docker-entrypoint-initdb.d/init-permissions.sh, postgres/16/postgresql.conf.sample
https://issues.redhat.com/browse/DBZ-6911
The PostgresSQL 16 images are not published yet so the CI will need to be re-run later.
=> DBZ-6911 Support for PostgreSQL 16

connect-base/2.5/Dockerfile, connect/2.5/Dockerfile, examples/mysql-gtids/2.5/Dockerfile, examples/mysql-gtids/2.5/mysql.cnf, examples/mysql-replication/master/2.5/master.cnf, examples/mysql/2.5/Dockerfile, examples/mysql/2.5/mysql.cnf
https://issues.redhat.com/browse/DBZ-6873
=> DBZ-6873 Upgrade to MySQL 8.2

server/2.6/Dockerfile, server/2.6/Dockerfile.local, server/snapshot/Dockerfile
https://issues.redhat.com/browse/DBZ-7385
=> DBZ-7385 reduce docker image size

connect/2.7/Dockerfile, connect/3.0/Dockerfile, connect/snapshot/Dockerfile
https://issues.redhat.com/browse/DBZ-8088
@jpechane, I'm not sure if these are the only places, can you double-check when back?
=> DBZ-8088 Add MariaDB to debezium/connect images

connect-base/3.0/Dockerfile
https://issues.redhat.com/browse/DBZ-8230
=> DBZ-8230 Bump apicurio from 2.4.1.Final to 2.6.2.Final

build-all-multiplatform.sh, postgres/16-alpine/Dockerfile, postgres/16/Dockerfile, postgres/17-alpine/Dockerfile, postgres/17-alpine/README.md, postgres/17-alpine/docker-entrypoint-initdb.d/init-permissions.sh, postgres/17-alpine/postgresql.conf.sample, postgres/17/Dockerfile, postgres/17/README.md, postgres/17/docker-entrypoint-initdb.d/init-permissions.sh, postgres/17/postgresql.conf.sample
https://issues.redhat.com/browse/DBZ-8275
Depends on https://github.com/debezium/postgres-decoderbufs/pull/31
Taking inspiration from c32a5cff3294ff4a8bbc905298d41efd77128fe9, I've added files for postgres v17. It might be possible to use Debian `bookworm` instead of `bullseye` as base image, but that's maybe for another discussion.
=> DBZ-8275 Support for PostgreSQL 17

server/3.0/Dockerfile
Creates `config` directory instead of `conf` to match the volume, which was changed in #392
=> Change mkdir conf for config to match volume

connect/snapshot/Dockerfile
So we can build conect 3.1 nightly image.
Should be switched back once we publish 3.1 conect-base image.
=> Temporarily switch to connect base 3.0

build-tool-images-multiplatform.sh, tooling/Dockerfile, tooling/LICENSE_kcctl.txt, tooling/README.md
Make the image arm device compatible with the following changes:
- Remove the build from kcat and install it via dnf install
- Remove the kcctl package download and build it instead
=> [tooling] Make image arm compatible

.github/workflows/image-builds-unauth.yml, conductor/3.1/Dockerfile
@jpechane Since the main CI tries to build the latest version, in this case 3.1, the relative folder is required. I preferred to create it so it will be ready for the release. There will be just the changes for repo patch an version.
=> DBZ-8605 Add 3.1 for conductor

examples/mysql-replication/master/2.7/inventory.sql, examples/mysql-replication/master/3.0/inventory.sql, examples/mysql-replication/master/3.1/inventory.sql
In the new base images replication is turned on (as it's turned on by default), but it's turned off temporarily while it executes initial scripts, so the `inventory` DB and initial data is not created on the replica.
https://issues.redhat.com/browse/DBZ-8655
=> DBZ-8655 Turn on replication during db initialization

base/latest/Dockerfile
https://issues.redhat.com/browse/DBZ-9035
=> DBZ-9035 Move Debezium base image to Fedora 41
